name: SmoothTP
version: '1.0-SNAPSHOT'
main: com.liquidskr.smoothTP.SmoothTP
api-version: '1.20'
commands:
  smtp:
    description: 플레이어간 텔레포트 기능을 제공합니다.
    usage: /<command> <x1> <y1> <z1> <yaw1> <pitch1> <x2> <y2> <z2> <yaw2> <pitch2> <speed>